/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiDecoreted;

import java.awt.CardLayout;
import javax.swing.JPanel;
import uiDecoreted.Tenant.CommentPanel;
import uiDecoreted.Tenant.TenantOrderPanel;
import uiDecoreted.Tenant.TenantPanel1;
import uiDecoreted.Tenant.TenantPanel2;
import uiDecoreted.Tenant.UserHomePanel;

/**
 *
 * @author wufan
 */
public class BasicUserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BasicUserJPanel
     */
    JPanel container;
    CardLayout cardLayout;
    public BasicUserJPanel(JPanel container) {
        this.container = container;
        initComponents();
        
        cardLayout = new CardLayout();
        rightjPanel.setLayout(cardLayout);
        rightjPanel.add("tP1",new TenantPanel1(rightjPanel));
        rightjPanel.add("tP2",new TenantPanel2(rightjPanel));
        rightjPanel.add("userhomeP",new UserHomePanel(rightjPanel));
        rightjPanel.add("tenantOrderP",new TenantOrderPanel(rightjPanel));
        rightjPanel.add("commentP",new CommentPanel(rightjPanel));
        cardLayout.show(rightjPanel,"tP1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightjPanel = new javax.swing.JPanel();
        pic1 = new javax.swing.JLabel();
        rentBtn = new javax.swing.JLabel();
        homeBtn = new javax.swing.JLabel();
        pic2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JLabel();
        userPic = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        menuBg = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rightjPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightjPanel.setOpaque(false);
        rightjPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(rightjPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1140, 810));

        pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/Icon-1.png"))); // NOI18N
        add(pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 40, 40));

        rentBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        rentBtn.setText("RENT");
        rentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rentBtnMousePressed(evt);
            }
        });
        add(rentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 100, 40));

        homeBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        homeBtn.setText("HOME");
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeBtnMousePressed(evt);
            }
        });
        add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 90, 40));

        pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/Icon-2.png"))); // NOI18N
        add(pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 40, 40));

        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backBtnMousePressed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 690, 80, 30));

        userPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userLayer/Userpic.png"))); // NOI18N
        add(userPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, 120));

        nameLabel.setBackground(new java.awt.Color(255, 255, 255));
        nameLabel.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Name");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 80, 30));

        menuBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userLayer/Menulayer-800.png"))); // NOI18N
        add(menuBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 810));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userLayer/Artboard 1@0.75x.png"))); // NOI18N
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMousePressed
        // TODO add your handling code here:
        container.remove(this);
//        Component[] components = container.getComponents();
//        Component component = components[components.length-1];
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backBtnMousePressed

    private void rentBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rentBtnMousePressed
        // TODO add your handling code here:
        cardLayout.show(rightjPanel,"tP1");
    }//GEN-LAST:event_rentBtnMousePressed

    private void homeBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMousePressed
        // TODO add your handling code here:
        cardLayout.show(rightjPanel,"userhomeP");
    }//GEN-LAST:event_homeBtnMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel homeBtn;
    private javax.swing.JLabel menuBg;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel pic1;
    private javax.swing.JLabel pic2;
    private javax.swing.JLabel rentBtn;
    private javax.swing.JPanel rightjPanel;
    private javax.swing.JLabel userPic;
    // End of variables declaration//GEN-END:variables
}
