/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiDecoreted;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author wufan
 */
public class MainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainJPanel
     */
    JPanel container;
    public MainJPanel(JPanel container) {
        this.container = container;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signInBtn = new javax.swing.JLabel();
        registerBtn = new javax.swing.JLabel();
        signinLayout = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signInBtnMousePressed(evt);
            }
        });
        add(signInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, 270, 60));

        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerBtnMousePressed(evt);
            }
        });
        add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 740, 110, 30));

        signinLayout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register/Sign In#8-75.png"))); // NOI18N
        add(signinLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Artboard 1@0.75x.png"))); // NOI18N
        bg.setText("jLabel2");
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void signInBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnMousePressed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)container.getLayout();
        container.add("2",new BasicUserJPanel(container));
        layout.next(container);
    }//GEN-LAST:event_signInBtnMousePressed

    private void registerBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMousePressed
        // TODO add your handling code here:
        RegisterJFrame registerJFrame = new RegisterJFrame();
        registerJFrame.setVisible(true);        
;
    }//GEN-LAST:event_registerBtnMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel registerBtn;
    private javax.swing.JLabel signInBtn;
    private javax.swing.JLabel signinLayout;
    // End of variables declaration//GEN-END:variables
}
