/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiDecoreted;

import Util.GlobalData;
import Util.JTextFieldHintListener;
import Util.SysData;
import Util.Tool;
import com.neu.infofinal.bean.UserAccount;
import uiDecoreted.Tenant.TenantUserPanel;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import uiDecoreted.Agency.AgencyPanel;
import uiDecoreted.LandLord.LandLordUserPanel;
import uiDecoreted.Manager.ManagerPanel;
import uiDecoreted.Housework.HouseworkPanel;
import uiDecoreted.Maintenance.MaintenancePanel;
import uiDecoreted.Mover.MovePanel;


/**
 *
 * @author wufan
 */
public class MainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainJPanel
     */
    JPanel container;
    public MainJPanel(JPanel container) {
        this.container = container;
        initComponents();
        
        usernametxt.addFocusListener(new JTextFieldHintListener(usernametxt, "Username",new Color(153,153,153)));
        passwordtxt.addFocusListener(new JTextFieldHintListener(passwordtxt, "Password",new Color(153,153,153)));
        foucstxt.requestFocusInWindow();
        
        GlobalData.getUserAccounts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernametxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JPasswordField();
        signInBtn = new javax.swing.JLabel();
        registerBtn = new javax.swing.JLabel();
        signinLayout = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        foucstxt = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernametxt.setBackground(new java.awt.Color(247, 247, 248));
        usernametxt.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        usernametxt.setForeground(new java.awt.Color(153, 153, 153));
        usernametxt.setText("Username");
        usernametxt.setToolTipText("");
        usernametxt.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 230, 40));

        passwordtxt.setBackground(new java.awt.Color(247, 247, 248));
        passwordtxt.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        passwordtxt.setForeground(new java.awt.Color(153, 153, 153));
        passwordtxt.setText("password");
        passwordtxt.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });
        add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 250, 40));

        signInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signInBtnMousePressed(evt);
            }
        });
        add(signInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, 270, 60));

        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerBtnMousePressed(evt);
            }
        });
        add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 740, 110, 30));

        signinLayout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register/Sign In#8-75.png"))); // NOI18N
        add(signinLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Artboard 1@0.75x.png"))); // NOI18N
        bg.setText("jLabel2");
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 810));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        foucstxt.setViewportView(jTextArea1);

        add(foucstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 470, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void signInBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnMousePressed
        // TODO add your handling code here:
        UserAccount userAccount = SysData.getUserAccount(usernametxt.getText(), String.valueOf(passwordtxt.getPassword()));
        if(userAccount==null){
            Tool.InfoString("Username or password is incorrect!");
            return;
        }
        CardLayout layout = (CardLayout)container.getLayout();
        if(SysData.ACCOUNT_TYPE.TENANT.getIndex()==userAccount.getType()){
            container.add("TenantUserPanel",new TenantUserPanel(container,userAccount));
        }else if(SysData.ACCOUNT_TYPE.LANDLORD.getIndex()==userAccount.getType()){
            container.add("LandLordUserPanel",new LandLordUserPanel(container,userAccount));
        }else if(SysData.ACCOUNT_TYPE.AGENCY.getIndex()==userAccount.getType()){
            container.add("AgencyPanel",new AgencyPanel(container,userAccount));
        }else if(SysData.ACCOUNT_TYPE.MANAGER.getIndex()==userAccount.getType()){
            container.add("ManagerPanel",new ManagerPanel(container,userAccount));
        }else if(SysData.ACCOUNT_TYPE.CLEANER.getIndex()==userAccount.getType()){
            container.add("HouseworkPanel",new HouseworkPanel(container,userAccount));
        }else if (SysData.ACCOUNT_TYPE.MAINTAINER.getIndex() == userAccount.getType()) {
            container.add("MaintenancePanel", new MaintenancePanel(container, userAccount));
        }else if (SysData.ACCOUNT_TYPE.MOVER.getIndex() == userAccount.getType()) {
            container.add("MovePanel", new MovePanel(container, userAccount));
        }
        layout.next(container);
        
    }//GEN-LAST:event_signInBtnMousePressed

    private void registerBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMousePressed
        // TODO add your handling code here:
        new registerJFrame().setVisible(true);       
    }//GEN-LAST:event_registerBtnMousePressed

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JScrollPane foucstxt;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JLabel registerBtn;
    private javax.swing.JLabel signInBtn;
    private javax.swing.JLabel signinLayout;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
