/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiDecoreted;

import Util.GlobalData;
import Util.JTextFieldHintListener;
import Util.SysData;
import uiDecoreted.Tenant.TenantUserPanel;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import uiDecoreted.Agency.AgencyPanel;
import uiDecoreted.Owner.OwnerUserPanel;
import uiDecoreted.Admin.AdminPanel;
import uiDecoreted.Housework.HouseworkPanel;
import uiDecoreted.Maintenance.MaintenancePanel;
import uiDecoreted.Move.MovePanel;


/**
 *
 * @author wufan
 */
public class MainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainJPanel
     */
    JPanel container;
    public MainJPanel(JPanel container) {
        this.container = container;
        initComponents();
        
        usernametxt.addFocusListener(new JTextFieldHintListener(usernametxt, "Username",new Color(153,153,153)));
        passwordtxt.addFocusListener(new JTextFieldHintListener(passwordtxt, "Password",new Color(153,153,153)));
        foucstxt.requestFocusInWindow();
        
        GlobalData.getUserAccounts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernametxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JPasswordField();
        housworkbtn = new javax.swing.JButton();
        maintenancebtn = new javax.swing.JButton();
        movebtn = new javax.swing.JButton();
        adminbtn = new javax.swing.JButton();
        ownerbtn = new javax.swing.JButton();
        agencybtn = new javax.swing.JButton();
        signInBtn = new javax.swing.JLabel();
        registerBtn = new javax.swing.JLabel();
        signinLayout = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        foucstxt = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernametxt.setBackground(new java.awt.Color(247, 247, 248));
        usernametxt.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        usernametxt.setForeground(new java.awt.Color(153, 153, 153));
        usernametxt.setText("Username");
        usernametxt.setToolTipText("");
        usernametxt.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 230, 40));

        passwordtxt.setBackground(new java.awt.Color(247, 247, 248));
        passwordtxt.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        passwordtxt.setForeground(new java.awt.Color(153, 153, 153));
        passwordtxt.setText("password");
        passwordtxt.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });
        add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 250, 40));

        housworkbtn.setText("houseworker");
        housworkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                housworkbtnActionPerformed(evt);
            }
        });
        add(housworkbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        maintenancebtn.setText("maintenance");
        maintenancebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenancebtnActionPerformed(evt);
            }
        });
        add(maintenancebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        movebtn.setText("move");
        movebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movebtnActionPerformed(evt);
            }
        });
        add(movebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        adminbtn.setText("admin");
        adminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminbtnActionPerformed(evt);
            }
        });
        add(adminbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, -1, -1));

        ownerbtn.setText("owner");
        ownerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerbtnActionPerformed(evt);
            }
        });
        add(ownerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 520, -1, -1));

        agencybtn.setText("agency");
        agencybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agencybtnActionPerformed(evt);
            }
        });
        add(agencybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        signInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signInBtnMousePressed(evt);
            }
        });
        add(signInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, 270, 60));

        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerBtnMousePressed(evt);
            }
        });
        add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 740, 110, 30));

        signinLayout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register/Sign In#8-75.png"))); // NOI18N
        add(signinLayout, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Artboard 1@0.75x.png"))); // NOI18N
        bg.setText("jLabel2");
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 810));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        foucstxt.setViewportView(jTextArea1);

        add(foucstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 470, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void signInBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnMousePressed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)container.getLayout();
        container.add("2",new TenantUserPanel(container,null));
        layout.next(container);
    }//GEN-LAST:event_signInBtnMousePressed

    private void registerBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMousePressed
        // TODO add your handling code here:
        new registerJFrame().setVisible(true);       
;
    }//GEN-LAST:event_registerBtnMousePressed

    private void ownerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerbtnActionPerformed
        // TODO add your handling code here:
       CardLayout layout = (CardLayout)container.getLayout();
       container.add("OwnerUserPanel",new OwnerUserPanel(container,null));
       layout.next(container);
    }//GEN-LAST:event_ownerbtnActionPerformed

    private void adminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminbtnActionPerformed
        // TODO add your handling code here:
       CardLayout layout = (CardLayout)container.getLayout();
       container.add("AdminPanel",new AdminPanel(container));
       layout.next(container);
    }//GEN-LAST:event_adminbtnActionPerformed

    private void agencybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agencybtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)container.getLayout();
       container.add("AgencyPanel",new AgencyPanel(container));
       layout.next(container);
    }//GEN-LAST:event_agencybtnActionPerformed

    private void housworkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_housworkbtnActionPerformed
        // TODO add your handling code here:
       CardLayout layout = (CardLayout)container.getLayout();
       container.add("HouseworkPanel",new HouseworkPanel(container));
       layout.next(container);
    }//GEN-LAST:event_housworkbtnActionPerformed

    private void maintenancebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenancebtnActionPerformed
        // TODO add your handling code here:
       CardLayout layout = (CardLayout)container.getLayout();
       container.add("MaintenancePanel",new MaintenancePanel(container));
       layout.next(container);
    }//GEN-LAST:event_maintenancebtnActionPerformed

    private void movebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movebtnActionPerformed
        // TODO add your handling code here:
       CardLayout layout = (CardLayout)container.getLayout();
       container.add("MovePanel",new MovePanel(container));
       layout.next(container);
    }//GEN-LAST:event_movebtnActionPerformed

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminbtn;
    private javax.swing.JButton agencybtn;
    private javax.swing.JLabel bg;
    private javax.swing.JScrollPane foucstxt;
    private javax.swing.JButton housworkbtn;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton maintenancebtn;
    private javax.swing.JButton movebtn;
    private javax.swing.JButton ownerbtn;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JLabel registerBtn;
    private javax.swing.JLabel signInBtn;
    private javax.swing.JLabel signinLayout;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
