/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiDecoreted;

import Util.JTextFieldHintListener;
import Util.SysData;
import Util.Tool;
import com.neu.infofinal.bean.Employee;
import com.neu.infofinal.bean.UserAccount;
import java.awt.Color;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author wufan
 */
public class registerJFrame extends javax.swing.JFrame {

    /**
     * Creates new form registerJFrame
     */
    String headimg;
    Boolean isReduplicated = false;
    public registerJFrame() {
        initComponents();
        
        usernametxt.addFocusListener(new JTextFieldHintListener(usernametxt, "Username",new Color(153,153,153)));
        passwordtxt.addFocusListener(new JTextFieldHintListener(passwordtxt, "Password",new Color(153,153,153)));
        phonetxt.addFocusListener(new JTextFieldHintListener(phonetxt, "Phone",new Color(153,153,153)));
        emailtxt.addFocusListener(new JTextFieldHintListener(emailtxt, "Email",new Color(153,153,153)));
        employeenametxt.addFocusListener(new JTextFieldHintListener(employeenametxt, "Name",new Color(153,153,153)));
        foucstxt.requestFocusInWindow();
        
        this.jRadioButton1.setSelected(true);
        headimg = "/images/userLayer/Userpic.png";
        
        usernametxt.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                checkUsername();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
               checkUsername();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
               checkUsername();
            }
 
        });
    }
    
    public void checkUsername(){
        UserAccount userAccount = SysData.getUserAccountByUsername(usernametxt.getText());
        if(userAccount!=null){
            isReduplicated = true;
            usernametxt.setForeground(Color.RED);
        }else{
            isReduplicated = false;
            usernametxt.setForeground(Color.BLACK);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbtn = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        create_img = new javax.swing.JLabel();
        userPic = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JTextField();
        phonetxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        employeenametxt = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        bg = new javax.swing.JLabel();
        foucstxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbtn.setFont(new java.awt.Font("Malayalam MN", 0, 13)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backbtn.setText("close");
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backbtnMousePressed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 20));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/WhiteBtn_s.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 70, 20));

        create_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        create_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                create_imgMousePressed(evt);
            }
        });
        getContentPane().add(create_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 670, 270, 70));

        userPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userLayer/Userpic.png"))); // NOI18N
        getContentPane().add(userPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 120, 120));

        usernametxt.setBackground(new java.awt.Color(247, 247, 248));
        usernametxt.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        usernametxt.setForeground(new java.awt.Color(153, 153, 153));
        usernametxt.setText("Username");
        usernametxt.setToolTipText("");
        usernametxt.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        getContentPane().add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 230, 40));

        passwordtxt.setBackground(new java.awt.Color(247, 247, 248));
        passwordtxt.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        passwordtxt.setForeground(new java.awt.Color(153, 153, 153));
        passwordtxt.setText("Password");
        passwordtxt.setToolTipText("");
        passwordtxt.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        passwordtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordtxtActionPerformed(evt);
            }
        });
        getContentPane().add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 230, 40));

        phonetxt.setBackground(new java.awt.Color(247, 247, 248));
        phonetxt.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        phonetxt.setForeground(new java.awt.Color(153, 153, 153));
        phonetxt.setText("Phone");
        phonetxt.setToolTipText("");
        phonetxt.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        getContentPane().add(phonetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 230, 40));

        emailtxt.setBackground(new java.awt.Color(247, 247, 248));
        emailtxt.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        emailtxt.setForeground(new java.awt.Color(153, 153, 153));
        emailtxt.setText("Email");
        emailtxt.setToolTipText("");
        emailtxt.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        emailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtxtActionPerformed(evt);
            }
        });
        getContentPane().add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 230, 40));

        employeenametxt.setBackground(new java.awt.Color(247, 247, 248));
        employeenametxt.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        employeenametxt.setForeground(new java.awt.Color(153, 153, 153));
        employeenametxt.setText("Name");
        employeenametxt.setToolTipText("");
        employeenametxt.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        employeenametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeenametxtActionPerformed(evt);
            }
        });
        getContentPane().add(employeenametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 230, 40));

        jRadioButton1.setText("Tenant");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton1MousePressed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, -1, -1));

        jRadioButton2.setText("HouseOwner");
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton2MousePressed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register/Signout#8-75.png"))); // NOI18N
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 800));

        foucstxt.setText("jTextField1");
        getContentPane().add(foucstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 760, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MousePressed
        // TODO add your handling code here:
//        this.jRadioButton1.setSelected(true);
        this.jRadioButton2.setSelected(false);
        headimg = "/images/userLayer/Userpic.png";
        userPic.setIcon(new javax.swing.ImageIcon(getClass().getResource(headimg)));
    }//GEN-LAST:event_jRadioButton1MousePressed

    private void jRadioButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MousePressed
        // TODO add your handling code here:
        this.jRadioButton1.setSelected(false);
//        this.jRadioButton2.setSelected(true);
        headimg = "/images/userLayer/Userpic2.png";
        userPic.setIcon(new javax.swing.ImageIcon(getClass().getResource(headimg)));
    }//GEN-LAST:event_jRadioButton2MousePressed

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_bgMousePressed

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_backMousePressed

    private void create_imgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_create_imgMousePressed
        // TODO add your handling code here:
        
        if(isReduplicated){
            Tool.InfoString("username is reduplicated!");
        }else{
            UserAccount userAccount = new UserAccount();
            userAccount.setUsername(usernametxt.getText());
            userAccount.setPassword(passwordtxt.getText());
            userAccount.setType(jRadioButton1.isSelected() ? 1 : 2);
            userAccount.setHeadpic(headimg);
            userAccount.setEmail(emailtxt.getText());
            userAccount.setPhone(phonetxt.getText());
            
            int insertUserAccount = SysData.insertUserAccount(userAccount);
            if(insertUserAccount<0){
                return;
            }
            UserAccount u = SysData.getUserAccountByUsername(userAccount.getUsername());
            Employee employee = new Employee();
            employee.setOrganizationId(1);
            employee.setEnterpriseId(1);
            employee.setUseraccountId(u.getId());
            employee.setName(employeenametxt.getText());
            int insertEmployee = SysData.insertEmployee(employee);
            if(insertEmployee>0){
                Tool.Success();
                setVisible(false);
            }
        }
    }//GEN-LAST:event_create_imgMousePressed

    private void passwordtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordtxtActionPerformed

    private void backbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMousePressed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_backbtnMousePressed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void employeenametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeenametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeenametxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel backbtn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel create_img;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField employeenametxt;
    private javax.swing.JTextField foucstxt;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JLabel userPic;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
