/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiDecoreted.LandLord;

import Util.GlobalData;
import Util.ImageRender;
import Util.Tool;
import com.neu.infofinal.bean.House;
import com.neu.infofinal.bean.UserAccount;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dengbowen
 */
public class LandLordManagePanel extends javax.swing.JPanel {

    /**
     * Creates new form OwnerRentPanel
     */
    UserAccount ownerAccount;
    JPanel rightcontainer;
    List<House> houses;
    public LandLordManagePanel(JPanel rightcontainer,UserAccount ownerAccount,List<House> houses) {
        initComponents();
        this.rightcontainer=rightcontainer;
        this.ownerAccount = ownerAccount;
        this.houses = houses;
        //改变table样式
        Tool.tableStyle1(jTable1,jScrollPane1);
        
        //DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       // model.setRowCount(0);
        displayHouseList();
    }
    
     public void displayHouseList() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jTable1.setRowHeight(105);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(new ImageRender());
        for (House house : houses) {
            Object[] row = new Object[5];
            //根据租客的id显示房子信息
            if (house.getOwnerId() == ownerAccount.getId()) {
                row[0] = house.getId();
                row[1] = house.getImage();
                // "<html><body><p align=\"center\">数据版本12312321321<br/>v1.0.0<br/>12321321</p></body></html>";
                row[2] = Tool.strToMultilineHTML(house.getAddress(), ",");
                row[3] = house.getPrice();
                row[4] = house.getAgencyId() == null? "Pending":"Completed";
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        refreshBtn = new javax.swing.JLabel();
        refresh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AddOrderBtn = new javax.swing.JLabel();
        AddOrder = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "HouseID", "Image", "Address", "Price", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(63, 164, 177));
        jTable1.setSelectionForeground(new java.awt.Color(153, 0, 204));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 850, -1));

        refreshBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        refreshBtn.setText("Refresh");
        refreshBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                refreshBtnMousePressed(evt);
            }
        });
        add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(912, 130, 70, 20));

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/WhiteBtn_s.png"))); // NOI18N
        add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HouseList");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 129, 41));

        AddOrderBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        AddOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddOrderBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddOrderBtn.setText("Add");
        AddOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddOrderBtnMousePressed(evt);
            }
        });
        add(AddOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 700, 200, 50));

        AddOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/Splash.png"))); // NOI18N
        add(AddOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 690, 200, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void AddOrderBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddOrderBtnMousePressed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout)rightcontainer.getLayout();
        cardLayout.show(rightcontainer, "addOrderP");
    }//GEN-LAST:event_AddOrderBtnMousePressed

    private void refreshBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshBtnMousePressed
        // TODO add your handling code here:
        displayHouseList();
    }//GEN-LAST:event_refreshBtnMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddOrder;
    private javax.swing.JLabel AddOrderBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel refresh;
    private javax.swing.JLabel refreshBtn;
    // End of variables declaration//GEN-END:variables
}
