/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiDecoreted.Owner;

import Util.ImageRender;
import Util.Tool;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dengbowen
 */
public class OwnerRentPanel extends javax.swing.JPanel {

    /**
     * Creates new form OwnerRentPanel
     */
    JPanel rightcontainer;
    public OwnerRentPanel(JPanel rightcontainer) {
        initComponents();
        this.rightcontainer=rightcontainer;
        //改变table样式
        Tool.tableStyle1(jTable1,jScrollPane1);
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        AddOrderBtn = new javax.swing.JLabel();
        AddOrder = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Image", "Address", "Price", "Status"
            }
        ));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(63, 164, 177));
        jTable1.setSelectionForeground(new java.awt.Color(153, 0, 204));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 850, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HouseList");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 129, 41));

        AddOrderBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        AddOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddOrderBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddOrderBtn.setText("Add");
        AddOrderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddOrderBtnMousePressed(evt);
            }
        });
        add(AddOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 700, 200, 50));

        AddOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/Splash.png"))); // NOI18N
        add(AddOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 690, 200, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void AddOrderBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddOrderBtnMousePressed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout)rightcontainer.getLayout();
        cardLayout.show(rightcontainer, "addOrderP");
    }//GEN-LAST:event_AddOrderBtnMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddOrder;
    private javax.swing.JLabel AddOrderBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
