/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiDecoreted.Maintenance;

import Util.JTextFieldHintListener;
import uiDecoreted.Housework.*;
import uiDecoreted.Tenant.*;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author tengfei
 */
public class ViewMaintanOrderDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form TenantPanel1
     */
    JPanel rightcontainer;
    public ViewMaintanOrderDetailPanel(JPanel rightcontainer) {
        this.rightcontainer = rightcontainer;
        initComponents();
        txtaddress.addFocusListener(new JTextFieldHintListener(txtaddress, "Username", new Color(153, 153, 153)));
        txtname.addFocusListener(new JTextFieldHintListener(txtname, "Name", new Color(153, 153, 153)));
        txtphone.addFocusListener(new JTextFieldHintListener(txtphone, "Phone", new Color(153, 153, 153)));
        txtarea.addFocusListener(new JTextFieldHintListener(txtarea, "Area", new Color(153, 153, 153)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JLabel();
        Backbak = new javax.swing.JLabel();
        housePic = new javax.swing.JLabel();
        leaveMessage = new javax.swing.JLabel();
        requesttour = new javax.swing.JLabel();
        txtarea = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        info = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backBtn.setText("Back");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backBtnMousePressed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, 50));

        Backbak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/Splash.png"))); // NOI18N
        add(Backbak, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 70));

        housePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/housepicture/housepic1.png"))); // NOI18N
        add(housePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 300, 210));

        leaveMessage.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        leaveMessage.setForeground(new java.awt.Color(255, 255, 255));
        leaveMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leaveMessage.setText("Leave a message");
        leaveMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                leaveMessageMousePressed(evt);
            }
        });
        add(leaveMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 690, 200, 60));

        requesttour.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        requesttour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        requesttour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/Splash.png"))); // NOI18N
        add(requesttour, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 690, 200, 60));

        txtarea.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        txtarea.setForeground(new java.awt.Color(153, 153, 153));
        txtarea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtarea.setToolTipText("");
        txtarea.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtareaActionPerformed(evt);
            }
        });
        add(txtarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 270, 40));

        txtphone.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        txtphone.setForeground(new java.awt.Color(153, 153, 153));
        txtphone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtphone.setToolTipText("");
        txtphone.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 270, 40));

        txtname.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(153, 153, 153));
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.setToolTipText("");
        txtname.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 270, 40));

        txtaddress.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        txtaddress.setForeground(new java.awt.Color(153, 153, 153));
        txtaddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtaddress.setToolTipText("");
        txtaddress.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 270, 40));

        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/housework/2@0,4x.png"))); // NOI18N
        add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 368, 608));
        info.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMousePressed

        CardLayout layout = (CardLayout)rightcontainer.getLayout();
        layout.show(rightcontainer, "ViewmtRequestPanel");
    }//GEN-LAST:event_backBtnMousePressed

    private void leaveMessageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaveMessageMousePressed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) rightcontainer.getLayout();
        layout.show(rightcontainer, "MessageMaintanPanel");
    }//GEN-LAST:event_leaveMessageMousePressed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtareaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backbak;
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel housePic;
    private javax.swing.JLabel info;
    private javax.swing.JLabel leaveMessage;
    private javax.swing.JLabel requesttour;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtarea;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
