/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiDecoreted.Housework;

import Util.Tool;
import com.neu.infofinal.bean.OrderHousework;
import uiDecoreted.Tenant.*;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Dengbowen
 */
public class MessageHouseworkPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommentPanel
     */
    JPanel rightcontainer;
    OrderHousework orderHousework;
    public MessageHouseworkPanel(JPanel rightcontainer,OrderHousework orderHousework) {
        initComponents();
        this.rightcontainer=rightcontainer;
        this.orderHousework=orderHousework;
        commentText.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commentText = new javax.swing.JTextField();
        backBtn = new javax.swing.JLabel();
        Backbak = new javax.swing.JLabel();
        submitBtn = new javax.swing.JLabel();
        submit = new javax.swing.JLabel();
        post = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        commentText.setText("Please enter you comment");
        add(commentText, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 560, 180));

        backBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backBtn.setText("Back");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backBtnMousePressed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, 60));

        Backbak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/Splash.png"))); // NOI18N
        add(Backbak, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, -1));

        submitBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submitBtn.setText("Submit");
        submitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                submitBtnMousePressed(evt);
            }
        });
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 200, 60));

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/Splash.png"))); // NOI18N
        add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        post.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userLayer/Input.png"))); // NOI18N
        post.setOpaque(true);
        add(post, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 580, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMousePressed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)rightcontainer.getLayout();
        layout.show(rightcontainer, "ViewHouseWorkOrderDetailPanel");
    }//GEN-LAST:event_backBtnMousePressed

    private void submitBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBtnMousePressed
        // TODO add your handling code here:
        orderHousework.setComment(this.commentText.getText());
        Tool.InfoString("Comment submitted!");

    }//GEN-LAST:event_submitBtnMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backbak;
    private javax.swing.JLabel backBtn;
    private javax.swing.JTextField commentText;
    private javax.swing.JLabel post;
    private javax.swing.JLabel submit;
    private javax.swing.JLabel submitBtn;
    // End of variables declaration//GEN-END:variables
}
