/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiDecoreted.Housework;

import Util.JTextFieldHintListener;
import Util.SysData;
import Util.Tool;
import com.neu.infofinal.bean.House;
import com.neu.infofinal.bean.OrderHousework;
import com.neu.infofinal.bean.UserAccount;
import uiDecoreted.Tenant.*;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author tengfei
 */
public class ViewHouseWorkOrderDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form TenantPanel1
     */
    JPanel rightcontainer;
    OrderHousework orderHousework;
    UserAccount tenantAccount;
    House tenantHouse; 
    public ViewHouseWorkOrderDetailPanel(JPanel rightcontainer,OrderHousework orderHousework,int tenantID) {
        this.rightcontainer = rightcontainer;
        this.orderHousework=orderHousework;
        tenantAccount=SysData.getUserAccountbyID(tenantID);

        initComponents();
        txtaddress.addFocusListener(new JTextFieldHintListener(txtaddress, "Username", new Color(153, 153, 153)));
        txtname.addFocusListener(new JTextFieldHintListener(txtname, "Name", new Color(153, 153, 153)));
        txtphone.addFocusListener(new JTextFieldHintListener(txtphone, "Phone", new Color(153, 153, 153)));
        txtemail.addFocusListener(new JTextFieldHintListener(txtemail, "Email", new Color(153, 153, 153)));
        txtearea.addFocusListener(new JTextFieldHintListener(txtearea, "Area", new Color(153, 153, 153)));
        getinfo();
        setinfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commentText = new javax.swing.JTextField();
        backBtn = new javax.swing.JLabel();
        Backbak = new javax.swing.JLabel();
        housePic = new javax.swing.JLabel();
        txtearea = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        info = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        commentText.setEditable(false);
        commentText.setText("No Comment Now");
        commentText.setOpaque(false);
        add(commentText, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 540, 120));

        backBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backBtn.setText("Back");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backBtnMousePressed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, 50));

        Backbak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/Splash.png"))); // NOI18N
        add(Backbak, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 70));

        housePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/housepicture/housepic1.png"))); // NOI18N
        add(housePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 300, 210));

        txtearea.setEditable(false);
        txtearea.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        txtearea.setForeground(new java.awt.Color(153, 153, 153));
        txtearea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtearea.setText("area");
        txtearea.setToolTipText("");
        txtearea.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtearea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteareaActionPerformed(evt);
            }
        });
        add(txtearea, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, 270, 40));

        txtemail.setEditable(false);
        txtemail.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        txtemail.setForeground(new java.awt.Color(153, 153, 153));
        txtemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtemail.setText("email");
        txtemail.setToolTipText("");
        txtemail.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 270, 40));

        txtphone.setEditable(false);
        txtphone.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        txtphone.setForeground(new java.awt.Color(153, 153, 153));
        txtphone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtphone.setText("phone");
        txtphone.setToolTipText("");
        txtphone.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 270, 40));

        txtname.setEditable(false);
        txtname.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(153, 153, 153));
        txtname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtname.setText("name");
        txtname.setToolTipText("");
        txtname.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 270, 40));

        txtaddress.setEditable(false);
        txtaddress.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        txtaddress.setForeground(new java.awt.Color(153, 153, 153));
        txtaddress.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtaddress.setText("address");
        txtaddress.setToolTipText("");
        txtaddress.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 250, 270, 40));

        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/housework/area@0,4x.png"))); // NOI18N
        add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 368, 608));
        info.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/housework/visuel@0,5x.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 560, 301));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMousePressed

        CardLayout layout = (CardLayout)rightcontainer.getLayout();
        layout.show(rightcontainer, "viewRequestP");
    }//GEN-LAST:event_backBtnMousePressed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txteareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteareaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backbak;
    private javax.swing.JLabel backBtn;
    private javax.swing.JTextField commentText;
    private javax.swing.JLabel housePic;
    private javax.swing.JLabel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtearea;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
    
    
    private void getinfo() {
        tenantHouse=SysData.getHouseByTenantId(tenantAccount.getId());
    }
    private void setinfo() {
//        this.txtaddress.setText(Tool.strToMultilineHTML(tenantHouse.getAddress(),","));
        this.txtaddress.setText(tenantHouse.getAddress());
        this.txtearea.setText(tenantHouse.getArea());
        this.txtemail.setText(tenantAccount.getEmail());
        this.txtphone.setText(tenantAccount.getPhone());
        this.txtname.setText(tenantAccount.getUsername());
        commentText.setText(orderHousework.getComment());
        housePic.setIcon(new javax.swing.ImageIcon(getClass().getResource(tenantHouse.getImage())));
    }


}
