/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiDecoreted.SystemAdmin;

import Util.SysData;
import Util.Tool;
import com.neu.infofinal.bean.Enterprise;
import com.neu.infofinal.bean.Organization;
import com.neu.infofinal.bean.UserAccount;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Dengbowen
 */
public class OrganizationPanel extends javax.swing.JPanel {

    /**
     * Creates new form NetworkPanel
     */
    Enterprise enterprise;
    JPanel rightcontainer;
    List<Organization> allOrganizations;
    SysadminPanel sysadminPanel;
    public OrganizationPanel(JPanel rightcontainer,SysadminPanel sysadminPanel ) {
        initComponents();
        this.sysadminPanel = sysadminPanel;
        this.rightcontainer=rightcontainer;
        this.enterprise=enterprise;
    }

    public void setEnterprise(Enterprise enterprise) {
        this.enterprise = enterprise;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        completedBtn = new javax.swing.JLabel();
        completed = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        organizationtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtenterprise = new javax.swing.JLabel();
        txtOrgType = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "ID", "Organization"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 850, 160));

        completedBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        completedBtn.setForeground(new java.awt.Color(255, 255, 255));
        completedBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completedBtn.setText("Add");
        completedBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                completedBtnMousePressed(evt);
            }
        });
        add(completedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 670, 200, 50));

        completed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/Splash.png"))); // NOI18N
        add(completed, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 660, 200, 70));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Enterprise Name:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Organization Type:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, 30));

        organizationtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationtxtActionPerformed(evt);
            }
        });
        add(organizationtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 240, 30));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Organization Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, -1, 30));

        txtenterprise.setText("name");
        add(txtenterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 380, 160, 30));

        txtOrgType.setText("type");
        add(txtOrgType, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 170, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void completedBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_completedBtnMousePressed
        // TODO add your handling code here:
        Organization organization = new Organization();
        organization.setName(organizationtxt.getText());
        organization.setEnterpriseId(enterprise.getId());
        int insertNetwork = SysData.insertOrganizaion(organization);
        if (insertNetwork > 0) {
            setInfo();
            sysadminPanel.setInfo();
            Tool.InfoString("Add Successfully");
        }
        
    }//GEN-LAST:event_completedBtnMousePressed

    private void organizationtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationtxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel completed;
    private javax.swing.JLabel completedBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField organizationtxt;
    private javax.swing.JLabel txtOrgType;
    private javax.swing.JLabel txtenterprise;
    // End of variables declaration//GEN-END:variables

    private void getInfo() {
        allOrganizations=SysData.getOrganizationByEnterpriseId(enterprise.getId());
    }

    public void setInfo() {
        getInfo();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (Organization organization : allOrganizations) {
            Object[] row = new Object[2];
            row[0] = organization.getId();
            row[1] = organization.getName();
            model.addRow(row);
        }

        txtenterprise.setText(enterprise.getName());
        String organizaitonType = "";
        if (enterprise.getType()==7) {
            organizaitonType = "Mover";
        } else if (enterprise.getType() == 5) {
            organizaitonType = "Cleaner";
        } else if (enterprise.getType() == 6) {
            organizaitonType = "Maintainer";
        }else if(enterprise.getType()==1){
            organizaitonType="House Agency";
        }
        txtOrgType.setText(organizaitonType);
    }
}
