/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiDecoreted.Tenant;

import Util.ImageRender;
import Util.SysData;
import Util.Tool;
import com.neu.infofinal.bean.House;
import com.neu.infofinal.bean.Region;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;

/**
 *
 * @author wufan
 */
public class RentalListPanel extends javax.swing.JPanel {

    /**
     * Creates new form RentalListPanel
     */
    List<House> houses;
    List<Region> allRegions;
    JPanel rightcontainer;
    public RentalListPanel(JPanel rightcontainer) {
        this.rightcontainer = rightcontainer;
        initComponents();
        
        //改变table样式
        
        Tool.tableStyle1(jTable1,jScrollPane1);
       
       
        
        districtCombo.removeAllItems();
        allRegions = SysData.getAllRegions();
        for (Region region : allRegions){
            districtCombo.addItem(region.getName());
        }
  
        
        displayHouseList();
    }

    public void setHouses(List<House> houses) {
        this.houses = houses;
    }
    
    
    
    public void displayHouseList() {
        houses = SysData.getAllHouses();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jTable1.setRowHeight(105);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(new ImageRender());
        for (House house : houses) {
            Object[] row = new Object[6];
            //如果house的租客id为空，代表没有租出去，显示
            if (house.getTenantId() == null && house.getRegion()==districtCombo.getSelectedIndex()) {
                row[0] = house.getId();
                row[1] = house.getImage();
                row[2] = Tool.strToMultilineHTML(house.getDescrib(), ",");  // "<html><body><p align=\"center\">数据版本12312321321<br/>v1.0.0<br/>12321321</p></body></html>";
                row[3] = Tool.strToMultilineHTML(house.getAddress(), ",");
                row[4] = house.getPrice();
                row[5] = allRegions.get(house.getRegion()).getName();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailBtn = new javax.swing.JLabel();
        detailBack = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        districtCombo = new javax.swing.JComboBox<>();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        detailBtn.setForeground(new java.awt.Color(255, 255, 255));
        detailBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailBtn.setText("Detail");
        detailBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                detailBtnMousePressed(evt);
            }
        });
        add(detailBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 200, 50));

        detailBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/Splash.png"))); // NOI18N
        add(detailBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, 200, 70));

        jTable1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "HouseId", "Image", "Desc", "Address", "Price", "Region"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setGridColor(new java.awt.Color(128, 128, 128));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(63, 164, 177));
        jTable1.setSelectionForeground(new java.awt.Color(153, 0, 204));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 960, -1));

        districtCombo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        districtCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        districtCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtComboActionPerformed(evt);
            }
        });
        add(districtCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 210, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void detailBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailBtnMousePressed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        //        System.out.println(row);
        if (row < 0) {
            Tool.InfoString("please select!");
            return;
        }
        int houseId = (int)jTable1.getValueAt(row,0);
        
        CardLayout cardLayout = (CardLayout)rightcontainer.getLayout();
        cardLayout.show(rightcontainer, "ViewDetailPanel");
        
        TenantUserPanel parent = (TenantUserPanel)rightcontainer.getParent();
        Component currnetComponent = rightcontainer.getComponent(parent.uiList.indexOf("ViewDetailPanel"));
        ViewDetailPanel viewDetailPanel = (ViewDetailPanel)currnetComponent;
        viewDetailPanel.setHouseInfo(houseId);
        
    }//GEN-LAST:event_detailBtnMousePressed

    private void districtComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtComboActionPerformed
        // TODO add your handling code here:
        int idx = districtCombo.getSelectedIndex();
        if(idx>=0)
        {
            displayHouseList();
        }
    }//GEN-LAST:event_districtComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detailBack;
    private javax.swing.JLabel detailBtn;
    private javax.swing.JComboBox<String> districtCombo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
