/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiDecoreted.Tenant;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Dengbowen
 */
public class TenantOrderPanel extends javax.swing.JPanel {

    /**
     * Creates new form TenantOrderPanel
     */
    JPanel rightcontainer;
    public TenantOrderPanel(JPanel rightcontainer) {
        initComponents();
        this.rightcontainer = rightcontainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        backBtn = new javax.swing.JLabel();
        Backbak = new javax.swing.JLabel();
        commentBtn = new javax.swing.JLabel();
        comment = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 850, 460));

        backBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backBtn.setText("Back");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backBtnMousePressed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, 200, 50));

        Backbak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/Splash.png"))); // NOI18N
        add(Backbak, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 200, 70));

        commentBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        commentBtn.setForeground(new java.awt.Color(255, 255, 255));
        commentBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        commentBtn.setText("Comment");
        commentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                commentBtnMousePressed(evt);
            }
        });
        add(commentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 710, 200, 50));

        comment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/Splash.png"))); // NOI18N
        add(comment, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 700, 200, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMousePressed
        // TODO add your handling code here:
        //        Component[] components = container.getComponents();
        //        Component component = components[components.length-1];
        CardLayout layout = (CardLayout)rightcontainer.getLayout();
        layout.show(rightcontainer, "userhomeP");
    }//GEN-LAST:event_backBtnMousePressed

    private void commentBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentBtnMousePressed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)rightcontainer.getLayout();
        layout.show(rightcontainer, "commentP");
    }//GEN-LAST:event_commentBtnMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backbak;
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel comment;
    private javax.swing.JLabel commentBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
