/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiDecoreted.Tenant;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author wufan
 */
public class UserHomePanel extends javax.swing.JPanel {

    /**
     * Creates new form TenantPanel1
     */
    JPanel rightcontainer;
    public UserHomePanel(JPanel rightcontainer) {
        this.rightcontainer = rightcontainer;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myOrderBtn = new javax.swing.JLabel();
        myOrderLable = new javax.swing.JLabel();
        housePic = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        roomLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myOrderBtn.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        myOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        myOrderBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        myOrderBtn.setText("My Order");
        add(myOrderBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, 200, 60));

        myOrderLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/White1.png"))); // NOI18N
        myOrderLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                myOrderLableMousePressed(evt);
            }
        });
        add(myOrderLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, -1, -1));

        housePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/housepicture/housepic1.png"))); // NOI18N
        add(housePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 300, 200));

        addressLabel.setText("Address");
        add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        roomLabel.setText("Superior Double Room");
        add(roomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userLayer/1_Contact.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 1100, 730));
    }// </editor-fold>//GEN-END:initComponents

    private void myOrderLableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myOrderLableMousePressed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout)rightcontainer.getLayout();
        cardLayout.show(rightcontainer, "tenantOrderP");
    }//GEN-LAST:event_myOrderLableMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel housePic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel myOrderBtn;
    private javax.swing.JLabel myOrderLable;
    private javax.swing.JLabel roomLabel;
    // End of variables declaration//GEN-END:variables
}
