/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiDecoreted.Tenant;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author wufan
 */
public class ViewDetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form TenantPanel1
     */
    JPanel rightcontainer;
    public ViewDetailPanel(JPanel rightcontainer) {
        this.rightcontainer = rightcontainer;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JLabel();
        Backbak = new javax.swing.JLabel();
        housePic = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        roomLabel = new javax.swing.JLabel();
        priceLabel1 = new javax.swing.JLabel();
        priceLabel3 = new javax.swing.JLabel();
        priceLabel4 = new javax.swing.JLabel();
        priceLabel5 = new javax.swing.JLabel();
        bookBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backBtn.setText("Back");
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backBtnMousePressed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, 50));

        Backbak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Button/Splash.png"))); // NOI18N
        add(Backbak, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 200, 70));

        housePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/housepicture/housepic1.png"))); // NOI18N
        add(housePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 300, 210));

        addressLabel.setText("Address");
        add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, -1, -1));

        priceLabel.setText("Price");
        add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 60, 30));

        roomLabel.setText("Superior Double Room");
        add(roomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, -1, -1));

        priceLabel1.setText("楼层");
        add(priceLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 60, 30));

        priceLabel3.setText("朝向");
        add(priceLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, 60, 30));

        priceLabel4.setText("户型");
        add(priceLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 60, 30));

        priceLabel5.setText("面积");
        add(priceLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 60, 30));

        bookBtn.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        bookBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookBtn.setText("约看Button");
        add(bookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 700, 140, 80));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel1.setText("签约Button");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 730, 130, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register/Line.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 700, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register/Line.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 700, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register/Line.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 700, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register/Line.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 700, 50));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userLayer/detailbackground.png"))); // NOI18N
        add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMousePressed
        // TODO add your handling code here:
//        Component[] components = container.getComponents();
//        Component component = components[components.length-1];
        CardLayout layout = (CardLayout)rightcontainer.getLayout();
        layout.show(rightcontainer, "tP1");
    }//GEN-LAST:event_backBtnMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backbak;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel backBtn;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bookBtn;
    private javax.swing.JLabel housePic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel priceLabel1;
    private javax.swing.JLabel priceLabel3;
    private javax.swing.JLabel priceLabel4;
    private javax.swing.JLabel priceLabel5;
    private javax.swing.JLabel roomLabel;
    // End of variables declaration//GEN-END:variables
}
